language: python

os:
  - linux

python:
  - '2.7'
  - '3.6'
  - '3.7'

before_install:
  - pip install pip setuptools --upgrade
  - pip install astropy

install:
  - python -m pip install .[doc]

before_script:
  - python -m pip install coveralls coverage codecov "pytest>=3.1" pytest-runner

script:
  # run unit tests
  - coverage run ./tests/test_basic.py

after_success:
  - coveralls
  - codecov

cache:
  pip: true
  apt: true