# Travis file for darepype

language: python

os:
  - linux

python:
  - '3.6'
  - '3.8'
  - '3.9'

install:
  - pip install pip setuptools --upgrade
  - pip install astropy
  - pip install configobj

script:
  # run unit tests - auto discover all test* in folder tests
  python -m unittest discover -s tests
  # - coverage run ./tests/test_basic.py - old program with coverage

after_success:
  - coveralls
  - codecov

cache:
  pip: true
  apt: true
  
# remember: results at https://travis-ci.com - 
# Used to be https://travis-ci.org. For migration details see
# https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide