# Travis file for darepype

language: python

os:
  - linux

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install pip setuptools --upgrade
  - pip install astropy
  - pip install configobj

script:
  # run unit tests - auto discover all test* in folder tests
  python -m unittest discover -s tests
  # - coverage run ./tests/test_basic.py - old program with coverage

after_success:
  - coveralls
  - codecov

cache:
  pip: true
  apt: true
  
# remember: results at https://travis-ci.org